version: '3'
services:
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"
  web:
    build: ./NotesAPI
    ports:
      - "5050:80"
    depends_on:
      - db