// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesAPI.Models;

namespace NotesAPI.Migrations
{
    [DbContext(typeof(NotesAPIContext))]
    partial class NotesAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotesAPI.Models.Checklist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item");

                    b.Property<int?>("NoteID");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("Checklist");
                });

            modelBuilder.Entity("NotesAPI.Models.Label", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelName");

                    b.Property<int?>("NoteID");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("NotesAPI.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Pinned");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("NotesAPI.Models.Checklist", b =>
                {
                    b.HasOne("NotesAPI.Models.Note")
                        .WithMany("Checklists")
                        .HasForeignKey("NoteID");
                });

            modelBuilder.Entity("NotesAPI.Models.Label", b =>
                {
                    b.HasOne("NotesAPI.Models.Note")
                        .WithMany("Labels")
                        .HasForeignKey("NoteID");
                });
#pragma warning restore 612, 618
        }
    }
}
