// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesApi.Models;

namespace NotesApi.Migrations
{
    [DbContext(typeof(NotesApiContext))]
    partial class NotesApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotesApi.Models.Checklists", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item");

                    b.Property<int?>("NotesID");

                    b.HasKey("ID");

                    b.HasIndex("NotesID");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("NotesApi.Models.Labels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelName");

                    b.Property<int?>("NotesID");

                    b.HasKey("ID");

                    b.HasIndex("NotesID");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("NotesApi.Models.Notes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Pinned");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NotesApi.Models.Checklists", b =>
                {
                    b.HasOne("NotesApi.Models.Notes")
                        .WithMany("Checklists")
                        .HasForeignKey("NotesID");
                });

            modelBuilder.Entity("NotesApi.Models.Labels", b =>
                {
                    b.HasOne("NotesApi.Models.Notes")
                        .WithMany("Labels")
                        .HasForeignKey("NotesID");
                });
#pragma warning restore 612, 618
        }
    }
}
